### ISSUE TITLE
Update string translations for v1.3.3

### ISSUE THREAD

**Issue by vokimon** [Som-Energia/new-api-webforms#10]
Strings are ready to be translated to euskara and galician.

**Comment by vokimon** [comment]
Strings to translate are bellow "Added or changed since 1.2.6" comment and above "Under development". The later strings are not required to be translated since they may change they are not visible yet.
Dani, confirm if you got this or either we will mail you.

**Comment by monfero** [comment]
OK. Mañana me pongo con el gallego y se lo paso también a los vascos.
